travis:
  secure:
    BINSTAR_TOKEN: QRlaCoIgbt6B07HnjOu6uhpjnVlTjn1cSE8A7/nRJBJaJEE+FYRDzZoA+Th6l87ytaRcJaVT+ZtUspR5+8tBHMDlBT9x4ZCzmeQljapOp+rcW+Zwj6mOmVWI4zK50bKHqgNmVNzGlu31snJvk0S2eXno5ELTHpWTl+CEQ1u60pmhS2Pyg9dKbp9kFKr1skzUGdE0Zfbt7pBLZ1ik+0JgjhplGm3CY/c0B9BJeaKNy572WnG3V057dIrDhriXnOaCJSB0FO1ddSEyeE5PO5RDWrZNcrbEfgOlaAm3t25vnM91U49kUjT+A426BjRywqJDyC06GXH3XIFI9ARUr66pZUC+t23pLoIweilMeOg9EO0ztl4GGBb1RbUXibVXsWe9VhfVmfns88eNNihkBF3dKMJDmFFng10TyrQvv/vmB435YIokJlqRva2GQiOFuug502DmUMp0P8cLOpnvBVfM/gK/BkIcCOXMC6s1Um/+wUt0NmmQaaVqmvWEZhPwW3MwOOrbgm+XwSBBccMJeuhuCeRDgCGAXSdu5LoDJMddL0GQtOhnBlrhHhgZGcuEmWHhi2spRioJQf0rc+BR9dUxFR1laM614WQ2tONiDnkxTrEu2YIlxEIrvDLmzGeAo4lCio+ns1Q8jE73/iYCU9Za/ZycY3mqpzbsSHgADP+9zF4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
