travis:
  secure:
    BINSTAR_TOKEN: r4U9FlaXr+UfIiBGBaXNRxrSboSYFfSDhGRcb1xd/I7Rutz9kG2oCXGpqwux6cfDMMYGhQzb+tSsGksOhvyzyjdntYKsKzkd8CBBjkcIWg3tIwX23lXAGa7b47+wFeUhZ1kQUh2FpJT3HexK+7YsGmyWaNY1MiXvBfHHGafHVH59XhMnS8Dz7kdW+oti/L6I9kaR15mj5bsFwYnjl4cMBTSYUnEC4ShsHPwzPr+snt6GodnKNcvMurAFQzAGCsPBW6mIxbV+tySidKq5ucuNSGbEwBeGgQM4gtI3VV0EASYn4KO+ZjMh52+Th5Y5hnbyqTD02XXzFAlKXyTo/nxEIVlaFU/ufD4MDNEGPfEbLP/I4lbB4uQUk2R1hR0C67c/uDQyftHp1F3i3RMwF9YktWEkkC5XBAd9vgYCT8UwcQnA7tqmrm077EUQpK7xEmIcbJtDpqaiPgdcxqYOyK4YkyIG6twccm2fL929CYNzVUUmexguHgFwctulibXFdNwkUDGzJ3+GFV4dUFPKgPdkEESjxS4uc68kiKMYnFwSYFojoMFjJVLSRE1FAuP+Zz7csBiadVIUD6O/GWGksdxyrzUtwRvWx6EiUxcRvjb2o+ArSnfNS54bXbOnpiAE4xYLARW7IaAFr5PgM826KUhRUAIo42nZ6ZeK6V3pBzQoeD0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
